# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Darian-Mars
version:      0.000
version_from: lib/Date/Darian/Mars.pm
installdirs:  site
requires:
    Math::BigInt:                  1.64
    Math::BigRat:                  0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
