---
name: Date-Darian-Mars
version: 0.001
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: the Darian calendar for Mars
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  base: 0
  constant: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
conflicts:
  Math::BigInt: < 1.64
  Math::BigRat: < 0.08
dynamic_config: 0
provides:
  Date::Darian::Mars:
    file: lib/Date/Darian/Mars.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
